services:
  app:
    build:
      context: .
      args:
        user: ${USER:-wallace}
        uid: ${UID:-1000}
      dockerfile: Dockerfile
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    restart: unless-stopped
    depends_on:
      - redis
      - queue
      - mysql
    networks:
      - tenant

  queue:
    build:
      context: .
      args:
        user: ${USER:-wallace}
        uid: ${UID:-1000}
      dockerfile: Dockerfile
    restart: always
    command: ["php", "artisan", "queue:work", "--sleep=3", "--tries=3"]
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
    networks:
      - tenant

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - tenant

  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 3307:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      LANG: C.UTF-8
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tenant

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - tenant

  mailpit:
    image: axllent/mailpit:latest
    restart: on-failure
    tty: true
    ports:
      - 1025:1025 # SMTP server
      - 8025:8025 # Web UI
    networks:
      - tenant

  stripe:
    image: "stripe/stripe-cli:latest"
    environment:
        STRIPE_SECRET: ${STRIPE_SECRET}
        STRIPE_DEVICE_NAME: ${STRIPE_DEVICE_NAME}
    command:
        stripe listen --forward-to http://172.17.0.1/stripe/webhook
    networks:
      - tenant

volumes:
  mysql-data:

networks:
  tenant:
    driver: bridge
